# Generated by Django 4.2.1 on 2023-06-08 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_blog_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_speciality', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
                ('start_time_of_apointment', models.TimeField()),
                ('date_of_appointment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
